# Generated by Django 5.1 on 2024-08-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="title",
            field=models.CharField(
                blank=True, default="No title", max_length=128, null=True
            ),
        ),
    ]
