# Generated by Django 5.1 on 2024-08-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_alter_chat_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="title",
            field=models.CharField(default="No title", max_length=128),
        ),
    ]
